- mlx_vlm/utils.py
- closes #14 
- added sample code in error message to show to create safetensors
> Better error message for non safetensor repository

- README.md
- mlx_vlm/chat_ui.py
- mlx_vlm/utils.py
- requirements.txt
This PR adds support for gradio as the default Chat UI.
You can start it via the CLI using this command:
``` sh
python -m mlx_vlm.chat_ui --model "<HF_REPO_OR_LOCAL_PATH>"
```
You can control `temperature` and `max_token` parameters from the UI.
Limitations:
- No support for multiple images.
- Chat without passing image.
Example:
> Add chat UI with gradio

- mlx_vlm/utils.py
The load_image function in mlx_vlm/utils.py is now updated to accept input as BytesIO representing base64 encoded images. This enhances the loading process by accommodating another type of input. Appropriate error handling has been added for potential IO errors.
> Update load_image function to handle BytesIO input

- mlx_vlm/models/llava_next/__init__.py
- mlx_vlm/models/llava_next/language.py
- mlx_vlm/models/llava_next/llava_next.py
- mlx_vlm/models/llava_next/vision.py
- mlx_vlm/prompt_utils.py
- mlx_vlm/tests/test_models.py
Changes:
- Add Llava-Next
Closes #42
> Add support for Llava-Next (v1.6)

- mlx_vlm/models/pixtral/pixtral.py
- mlx_vlm/models/pixtral/vision.py
1. [IMG_BREAK] and [IMG_END] are lost after embedding
2. image position encode should be done per image base https://github.com/mistralai/mistral-inference/blob/main/src/mistral_inference/vision_encoder.py#L85 https://github.com/huggingface/transformers/blob/main/src/transformers/models/pixtral/modeling_pixtral.py#L492
> Fix issues with multiple image handling

- mlx_vlm/LORA.MD
- mlx_vlm/generate.py
- mlx_vlm/lora.py
- mlx_vlm/models/base.py
- mlx_vlm/models/idefics2/language.py
- mlx_vlm/models/llava/language.py
- mlx_vlm/models/llava_bunny/language.py
- mlx_vlm/models/llava_next/language.py
- mlx_vlm/models/mllama/__init__.py
- mlx_vlm/models/mllama/language.py
- mlx_vlm/models/mllama/mllama.py
- mlx_vlm/models/mllama/vision.py
- mlx_vlm/models/multi_modality/language.py
- mlx_vlm/models/paligemma/language.py
- mlx_vlm/models/phi3_v/phi3_v.py
- mlx_vlm/models/pixtral/language.py
- mlx_vlm/models/qwen2_vl/language.py
- mlx_vlm/models/qwen2_vl/qwen2_vl.py
- mlx_vlm/prompt_utils.py
- mlx_vlm/tests/test_models.py
- mlx_vlm/tests/test_trainer.py
- mlx_vlm/trainer/trainer.py
- mlx_vlm/trainer/utils.py
- mlx_vlm/utils.py
Adds support for Llama Vision, streamlined resize image and formated language model output.
Closes #60
> Add support for Llama-3.2-vision & Resize image

- mlx_vlm/prompt_utils.py
Puts image references at the beginning of the prompt to Pixtral to make prompting more natural - without using "following" which the API user is likely not aware of. Fixes #98.
> fix pixtral image prompt order for doc VQA

- mlx_vlm/models/qwen2_vl/language.py
- mlx_vlm/models/qwen2_vl/qwen2_vl.py
This PR improves Qwen2-VL inference speed by 20% for 8bit and 33% for 4bit on M3 Max 96GB.
And a staggering 64% for 4bit improvement on M2 Ultra 192GB.
Thanks to @awni!
Closes #110
> Qwen2-VL performance improvements

- mlx_vlm/models/qwen2_vl/language.py
- mlx_vlm/models/qwen2_vl/qwen2_vl.py
- mlx_vlm/models/qwen2_vl/vision.py
- Remove the specialized RoPE in the language model as it is equivalent to a regular RoPE in that case. Using the MLX fast RoPE is also faster
- Avoid accidentally upcasting everything to fp32. This can make a big difference in memory use, especially for lots of images or a videos.
> Faster / more memory efficient Qwen VL

- mlx_vlm/utils.py
This PR implements lazy evaluation during the model loading and conversion process to improve memory efficiency. By utilizing MLX's lazy evaluation feature, we defer actual memory allocation until weights are needed.
- Added lazy=True parameter when fetching models from HuggingFace hub
- Memory allocation now happens on-demand rather than eagerly
- Works with both float16 (quantized) and user-specified dtype configurations
- Reduced peak memory usage during model conversion
- Smoother handling of large models, particularly when converting to float16
- Maintains compatibility with existing model loading workflows
Read more here: https://ml-explore.github.io/mlx/build/html/usage/lazy_evaluation.html
> Add lazy eval during conversion

- mlx_vlm/tokenizer_utils.py
Seeing this warning:
```
ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/neil/.cache/lm-studio/models/mlx-community/pixtral-12b-4bit/tokenizer.json' mode='r' encoding='UTF-8'>
tokenizer_content = json.load(tokenizer_file.open())
```
This PR fixes this warning by closing the tokenizer file after reading it.
> Open tokenizer.json within context manager

- mlx_vlm/utils.py
This breaks stream generation if the model doesn't have image_token_index
> Fix broken stream generate for SmolVLM and others

- mlx_vlm/models/idefics3/idefics3.py
- mlx_vlm/prompt_utils.py
- Corrects the image token placement strategy by moving tokens from last position to first position
- Resolves missing image token index (tracked in issue #132)
- Modified token placement algorithm to insert image tokens at the beginning of the sequence instead of appending them at the end
- Implemented proper index tracking and reporting for image tokens
- Added validation to ensure token indices are correctly maintained
Sample menu section used for testing:
Token placement and index reporting issues visible in these screenshots:
Correct token placement and index reporting:
- Verified token placement in multiple scenarios
- Confirmed correct index reporting across different image types
- Validated backwards compatibility with existing implementations
- Fixes #132 (Missing image token …
> Fix idefics3

- mlx_vlm/models/mllama/language.py
This PR introduces language only support significant improvements in generation speed and memory usage for **Llama-3.2-11B-Vision-Instruct-4bit on MLX-VLM**. Below are the key metrics comparing `before` and `after` performance, along with their percentage changes:
Metric | Before | After | % Diff
-- | -- | -- | --
Prompt Tokens/sec | 2.807 | 2.825 | +0.64%
Generation Tokens/sec | 0.362 | 6.692 | +1749%
Peak Memory (GB) | 65.453 | 16.252 | -75.2%
<h3>Key Improvements</h3>
<ol>
<li><strong>Generation Speed</strong>: We achieved nearly an 18x increase in tokens generated per second.</li>
<li><strong>Memory Efficiency</strong>: Reduced peak memory usage by approximately 75%.</li>
<li><strong>Slightly Faster Prompt Handling</strong>: Prompt ingestion speed improved by about 0.64%.</li>
</ol> …
> Fix Llama-3.2-Vision

- README.md
The example on the readme does not run because the order of parameters is incorrect resulting in:
`TypeError: TextEncodeInput must be Union[TextInputSequence, Tuple[InputSequence, InputSequence]]`
Fixing example on Readme
> Corrected order of parameters on example

- mlx_vlm/convert.py
- mlx_vlm/utils.py
Check the `torch_dtype` in the hf-model before starting conversion. We need this because precision is lost when casting from `bfloat16` to `float16`
- Remove the `ignored if -q is given` from the help text, since it's not true and it does indeed affect the quantization quality
- Check if the `torch_dtype` top-level field in the hf-model's config.json matches one of our three dtypes. If it does, and the user has not specified a dtype, use `torch_dtype`
- If `torch_dtype` isn't found, or if the value isn't one we expect, we default to `bfloat16`. More and more models need `bfloat16` to work well, so this is a better default moving forward
> When converting models, default dtype to config.json's torch_dtype

- mlx_vlm/LORA.MD
Fixing an inconsistency with the docs; the use of dash (-) instead of underscore (_) for the LORA.md command-line parameters should be consistently applied.
> docs: Fix command-line params in LORA.md to use dash separators

- mlx_vlm/models/internvl_chat/vision.py
when running with InternVL3 ,you will get an error:
```
self.q_norm(queries.transpose(1, 2).flatten(-2, -1))
ValueError: [transpose] Recived 2 axes for array with 4 dimensions.
```
This commit fixed it by replacing `transpose(1, 2)` with `transpose(0, 2, 1, 3)`
> fix models/internvl_chat/vision.py transpose issue

- mlx_vlm/tests/test_utils.py
- test that reset replaces eos_token_ids and that StoppingCriteria is callable
- `python -m pytest -q` *(fails: No module named pytest)*
- `pip install pytest` *(fails: could not find a version)*
> Add test for StoppingCriteria.reset

- README.md
- correct a typo in the POST request example
- `pre-commit` *(fails: command not found)*
> Fix README POST request typo

- mlx_vlm/utils.py
- correct early return when no EOS tokens are provided
- `python -m unittest discover -v` *(fails: No module named 'mlx')*
> Fix add_eos_token_ids early exit

- mlx_vlm/models/aya_vision/language.py
- mlx_vlm/models/gemma3/language.py
- mlx_vlm/models/idefics2/language.py
- mlx_vlm/models/idefics3/language.py
- mlx_vlm/models/llava/language.py
- mlx_vlm/models/llava_bunny/language.py
- mlx_vlm/models/llava_next/language.py
- mlx_vlm/models/multi_modality/language.py
- mlx_vlm/models/paligemma/language.py
- mlx_vlm/models/phi3_v/language.py
- mlx_vlm/models/pixtral/language.py
- add `max_position_embeddings` field to all `TextConfig` dataclasses across language models
Closes https://github.com/Blaizzy/mlx-vlm/issues/353
- `black mlx_vlm/models/phi3_v/language.py mlx_vlm/models/gemma3/language.py mlx_vlm/models/idefics2/language.py mlx_vlm/models/idefics3/language.py mlx_vlm/models/llava/language.py mlx_vlm/models/llava_bunny/language.py mlx_vlm/models/llava_next/language.py mlx_vlm/models/multi_modality/language.py mlx_vlm/models/paligemma/language.py mlx_vlm/models/phi3_v/language.py mlx_vlm/models/pixtral/language.py`
- `isort mlx_vlm/models/aya_vision/language.py mlx_vlm/models/gemma3/language.py mlx_vlm/models/idefics2/language.py mlx_vlm/models/idefics3/language.py mlx_vlm/models/llava/language.py mlx_vlm/models/llava_bunny/language.py …
> Add max_position_embeddings to TextConfig dataclasses

- docs/overrides/main.html
- mkdocs.yml
- update mkdocs metadata for MLX-VLM
- remove placeholder documentation files
- `pip install -q -r requirements.txt` *(fails: Could not find mlx>=0.25.0 due to proxy issues)*
- `pytest -s ./tests --ignore=tests/test_smoke.py` *(fails: command not found)*
> Update mkdocs configuration

- mlx_vlm/utils.py
This message is often misleading, as it shows even for completely unrelated `huggingface/transformers` processing errors.
For example, if you send a prompt without image markers, such as `"hi"`, into `generate()` alongside any number of images, for models like Gemma 3, Llama 4, InternVL, aya vision, you get an error message containing `Please install PyTorch and try again`:
```
ValueError: Failed to process inputs with error: Prompt contained 0 image tokens but received 1 images. Please install PyTorch and try again.
```
Even if you have PyTorch already installed - and the error has nothing to do with PyTorch installation.
Furthermore, if you don't have PyTorch installed, the error message already contains `PyTorch is not installed`:
```
ValueError: Failed to process inputs with error: …
```
> Remove hardcoded pytorch install error message

- mlx_vlm/models/qwen2_5_vl/qwen2_5_vl.py
- mlx_vlm/models/qwen2_vl/qwen2_vl.py
Hello @Blaizzy, I have figured out the issue with Qwen-VL models having a hard time understanding multiple images or images in multi-turn. It turns out that the way we replace the vision tokens with embeddings was not correct. The following implementation have fixed these issue. This also fixes for images being passed during multi-turn conversation.
This is the script used to test:
```python
from mlx_vlm import load, apply_chat_template, generate
from mlx_vlm.utils import load_image
from mlx_vlm.utils import process_image
qwen_vl_model, qwen_vl_processor = load("mlx-community/Qwen2.5-VL-7B-Instruct-4bit")
qwen_vl_config = qwen_vl_model.config
images = [
"./mlx-vlm/examples/images/cats.jpg",
"./mlx-vlm/examples/images/desktop_setup.png",
]
message = [
{
"role": "user",
"content": [ …
```
> Fix multi images understand for Qwen2 and Qwen2.5 VL

- mlx_vlm/models/gemma3n/language.py
When quantizing the `Gemma3nTextScaledWordEmbedding` module, it follows this code path:
- https://github.com/ml-explore/mlx/blob/2c11d10/python/mlx/nn/layers/embedding.py#L42
- https://github.com/ml-explore/mlx/blob/2c11d10/python/mlx/nn/layers/quantized.py#L138
Which ends up overwriting the `Gemma3nTextScaledWordEmbedding` instance with `QuantizedEmbedding`. This means that `Gemma3nTextScaledWordEmbedding.__call__` never gets called when the model is quantized.
Fix this issue by moving the scaling outside of `Gemma3nTextScaledWordEmbedding` and deleting `Gemma3nTextScaledWordEmbedding`.
@awni : I would be curious to hear your thoughts on how to enable the use case of inheriting from `nn.Embeddings` while correctly quantizing the underlying weights in the base class.
> [gemma3n] Correctly scale text embeddings for quantized gemma3n conversions

- pyproject.toml
- requirements.txt
This PR makes UI (gradio) and audio (mlx-audio) dependencies optional to reduce the installation footprint for users who don't need these features.
- ✅ Removed `gradio>=5.19.0` from `requirements.txt`
- ✅ Removed `mlx-audio` from `requirements.txt`
- ✅ Added optional dependencies in `pyproject.toml`:
- `ui = ["gradio>=5.19.0"]`
- `audio = ["mlx-audio"]`
After this change, users can install mlx-vlm with different dependency sets:
- **Base installation**: `pip install mlx-vlm`
- **With UI support**: `pip install mlx-vlm[ui]`
- **With audio support**: `pip install mlx-vlm[audio]`
- **With both**: `pip install mlx-vlm[ui,audio]`
- Reduces installation size for users who don't need UI or audio features
- Provides flexibility in choosing required dependencies
- Follows Python packaging best …
> Make UI and audio dependencies optional

- mlx_vlm/models/lfm2_vl/lfm2_vl.py
For https://github.com/lmstudio-ai/mlx-engine/pull/209 and other integrations of LFM2-VL, we'd like `merge_input_ids_with_image_features` to be a public static method. Additionally: does not change behavior within mlx-vlm, and improves readability as to the true inputs to the function
> External access to LFM2-VL merge-input-IDs method

- mlx_vlm/models/glm4v_moe/language.py
Fix https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/912
```python
Error in iterating prediction stream: AttributeError: 'LanguageModel' object has no attribute 'n_kv_heads'
```
> Add n_kv_heads property used in LM Studio to glm4v_moe.LanguageModel

- mlx_vlm/models/glm4v_moe/language.py
> Fix: rope rotation (GLM-4.5v)
