mlx_vlm/chat_ui.py
=> fix llava template

mlx_vlm/models/idefics2/idefics2.py, mlx_vlm/models/idefics2/language.py, mlx_vlm/models/llava/language.py, mlx_vlm/models/llava/llava.py, mlx_vlm/models/llava_bunny/language.py, mlx_vlm/models/llava_bunny/llava_bunny.py, mlx_vlm/models/llava_next/language.py, mlx_vlm/models/llava_next/llava_next.py, mlx_vlm/models/multi_modality/language.py, mlx_vlm/models/multi_modality/multi_modality.py, mlx_vlm/models/paligemma/language.py, mlx_vlm/models/phi3_v/phi3_v.py, mlx_vlm/models/pixtral/__init__.py, mlx_vlm/models/pixtral/language.py, mlx_vlm/models/pixtral/pixtral.py, mlx_vlm/models/pixtral/vision.py, mlx_vlm/models/qwen2_vl/vision.py, mlx_vlm/prompt_utils.py, mlx_vlm/utils.py
Add support for Pixtral, refactoring and fixing compatibility issues instroduced in #59 
closes #65
=> Add support for Pixtral-12B

mlx_vlm/models/qwen2_vl/language.py, mlx_vlm/models/qwen2_vl/qwen2_vl.py, mlx_vlm/tests/test_models.py
The prefix issue was resolved, however creating PR with the logic refactored as requested by @Blaizzy in https://github.com/Blaizzy/mlx-vlm/issues/61
=> Added: Qwen2-VL Unit Tests, Refactored Weight Sanitization

README.md
Add load_config to the two example scripts in the readme so that they function as intended
=> Fix example scripts in the readme.md to import and use load_config

mlx_vlm/models/qwen2_vl/qwen2_vl.py, mlx_vlm/models/qwen2_vl/vision.py
=> Qwen2-VL Improvements (1-2x speedup)

.github/workflows/tests.yml, mlx_vlm/models/qwen2_vl/qwen2_vl.py, mlx_vlm/utils.py
Closes: https://github.com/lmstudio-ai/mlx-engine/issues/27
=> Fix Qwen2-VL OCR and repetition penalty

mlx_vlm/utils.py
=> Fix padding type casting

mlx_vlm/models/paligemma/language.py, mlx_vlm/models/paligemma/paligemma.py, mlx_vlm/models/paligemma/vision.py
=> Add support for paligemma2

mlx_vlm/models/deepseek_vl_v2/deepseek_vl_v2.py
This PR introduces critical improvements and optimizations for multi-image inference, resulting in significant performance gains.
1. **Fixes Multi-Image Inference**  
Resolved issues to ensure correct and efficient handling of multi-image inputs.
2. **Achieves ~2x Speedup**  
Improved processing efficiency for both prompt handling and token generation, nearly doubling performance.
Performance remains consistent and stable, as shown below:  
Significant improvements are evident in multi-image inference, as illustrated below:
=> Fix multi-image and 2x speed improvements (DS-VL2)

mlx_vlm/__init__.py, mlx_vlm/tests/test_smoke.py, mlx_vlm/tests/test_utils.py, mlx_vlm/utils.py
=> Fix skip-vision predicate and add utils unit test (quantize and inputs)

mlx_vlm/models/qwen2_vl/vision.py, mlx_vlm/tests/test_trainer.py, mlx_vlm/trainer/trainer.py
=> Fix trainer and Qwen2-VL

computer_use/autonomous_gui_agent.py
This should fix the local path to the audio file
I think you meant to use this model? I see others under [mlx-community](https://huggingface.co/mlx-community) like 8/6/4bit
mlx-community/ShowUI-2B-bf16-bf16
=> Fix typo and local path

mlx_vlm/models/gemma3/gemma3.py, mlx_vlm/models/gemma3/language.py, mlx_vlm/utils.py, mlx_vlm/video_generate.py
This PR introduces processing with fallback to accomodate Mistral Small that only returns torch tensors.
=> Fix return tensors  

mlx_vlm/models/gemma3/language.py
Copied from @awni [here](https://github.com/ml-explore/mlx-lm/pull/39)
=> chore: fix sliding mask

README.md
=> docs: add note on PIL

mlx_vlm/models/gemma3/language.py
Float16 has a max value of 65504. When values exceed this limit, they become inf.
- Example: 
If x contains 70000.0 in float16, it becomes inf, causing gradient issues. We upcast to float32 for operations that might exceed the limit, then clip and convert back to float16 to maintain numerical stability.
=> Gemma 3 - Clip fp16 activations

mlx_vlm/utils.py
=> Remove duplicate get_model_path

mlx_vlm/models/gemma3/gemma3.py, mlx_vlm/models/qwen2_5_vl/qwen2_5_vl.py
Since the required inputs from these functions were previously just 2-3 config values, making these public static clarifies the inputs to the functions, and allows for external import as a modular unit
=> Make Gemma3 and Qwen2.5VL text-image input merging functions public static

mlx_vlm/models/gemma3/gemma3.py
This PR fixes a bug introduces in #335 
closes #242
=> Fix: remove self reference in static method prepare_inputs_for_multimodal

mlx_vlm/models/gemma3/gemma3.py, mlx_vlm/models/internvl_chat/vision.py, mlx_vlm/models/kimi_vl/vision.py, mlx_vlm/models/multi_modality/vision.py, mlx_vlm/tests/test_models.py
Fixes bug introduced in #342 and adds tests to avoid regression.
Models affected:
- gemma3
- internvl-3
- kimi_vl
- deepseekvl-chat
=> Fix VLMs upcasting

mlx_vlm/models/mistral3/mistral3.py
The Mixtral3 model inherits from Pixtral, which already implements a near duplicate ([link](https://github.com/Blaizzy/mlx-vlm/blob/2c3014fd40962bd5320ad611502e7e26cae08926/mlx_vlm/models/pixtral/pixtral.py#L108-L130)) of the _merge_input_ids_with_image_features method. This PR modified Mixtral3 to use the existing implementation in the parent class.
This extends the work from PR #355 to use `mlx-vlm` to modularly compute image embeddings as outlined in @mattjcly's [blog post](https://lmstudio.ai/blog/unified-mlx-engine).
=> De-duplicate Mixtral3's merge_input_ids_with_image_features

mlx_vlm/models/gemma3n/vision.py
Command: `python -m mlx_vlm.generate --temp 0.0 --model ./gemma-3n-E2B-it-bf16 --image https://raw.githubusercontent.com/lmstudio-ai/mlx-engine/refs/heads/main/demo-data/toucan.jpeg --prompt 'describe this'`
Reference results (transformers==4.53.0 timm==1.0.16):
```
**This is a stunning close-up photograph of a vibrant toucan perched on a mossy branch.**
Here's a breakdown of what's depicted:
* **The Toucan:** The star of the image is a toucan, easily recognizable by its enormous, colorful beak. The beak is a striking blend of yellow, orange, red, and blue, with a prominent black tip. 
* **Coloration:** The toucan's body is primarily black, contrasting beautifully with its bright yellow chest and neck. Hints of red and orange can be seen on its wings and tail.
* **Pose:** The toucan is …
```
=> [gemma3n] Fix vision encoder implementation of EdgeResidual and UniversalInvertedResidual

mlx_vlm/chat.py, mlx_vlm/chat_ui.py, mlx_vlm/video_generate.py
=> fix(chat-ui): Fix imports, blocking Chat-ui server start

mlx_vlm/models/gemma3n/gemma3n.py
The [mlx-engine](https://github.com/lmstudio-ai/mlx-engine) [unified architecture](https://lmstudio.ai/blog/unified-mlx-engine) uses mlx-vlm to compute text and image embeddings for multi-modal prompts.
This PR modifies the Gemma3n `Model` to expose static hooks that can be used to generate input embeddings for text + image prompts. I have not made the analogous changes to audio pathways, as the audio modality is not supported by mlx-engine.
=> [Gemma3n] Add hooks for image embedding computation

mlx_vlm/convert.py, mlx_vlm/generate.py, mlx_vlm/utils.py, requirements.txt
=> Remove scipy dep

mlx_vlm/utils.py
Closes #445 
You can now pass BytesIO objects or a base64 encoded string
=> Fix base64 encoded images

examples/video_understanding.ipynb
=> Fix video understanding NB
